"""boyin个人vim配置"""

""Vundle配置
source $HOME/configure/vim/vundlerc

""基础设置
syntax on           " 语法高亮
set nobackup        " 设置无备份文件
set backupcopy=yes  " 设置备份时的行为为覆盖
set noswapfile      " 设置无临时文件
set vb t_vb=        " 关闭提示音
set isk+=-          " 将-连接符也设置为单词

set autoread        " 当文件在外部被修改,自动更新该文件
set hlsearch        " 高亮搜索
set incsearch       " 在输入要搜索的文字时,事实匹配
set ignorecase      " 搜索模式里忽略大小写
set smartcase       " 如果搜索模式包含大写字符,有以上选项才有效
set ruler           " 显示行列号
set colorcolumn=80  " 高亮第80列
hi ColorColumn ctermbg=4  " 灰色

""缓存清理
" autocmd FileType netrw setlocal bufhidden=delete
""目录列表样式tree
" let g:netrw_liststyle= 3

set list
set listchars=tab:│\ 
set listchars+=trail:·
set listchars+=extends:❯
set listchars+=precedes:❮

set autoindent      " 自动缩进
""set cindent         " 以C语言的方式缩进
set shiftwidth=2    " 设置自动缩进的空格数量
set softtabstop=2   " tab键的实际占有空格数，统一缩进
set tabstop=2       " 设置tab键的空格数
set expandtab       " 将tab键转换为空格
""set backspace=2   " 退格键可以删除任何东西

set foldenable         " 启用折叠
set foldmethod=marker  " marker 折叠方式

""keys 配置

""Shiftless
noremap ; :

""窗口切换 <c-k,j,h,l,c>
noremap <c-k> <c-w>k
noremap <c-j> <c-w>j
noremap <c-h> <c-w>h
noremap <c-l> <c-w>l
noremap <c-c> <c-w>c

""插入模式 <c-k,j,h,l,u>
inoremap fj <esc>
inoremap <c-k> <up>
inoremap <c-j> <down>
inoremap <c-h> <left>
inoremap <c-l> <right>
inoremap <c-u> <end>

" --- leader keys ---
let mapleader=","  "修改leader键为逗号

" edit .vimrc
nmap <leader>e :e ~/.vimrc<cr>
nmap <leader>r :source ~/.vimrc<cr>

nnoremap <leader><space> :noh<cr>  "使用<leader>空格来取消高亮
nnoremap <leader>p :set paste!<cr>  "切换粘帖模式

" 文件类型切换
nmap <leader>fh :set ft=html<cr>
nmap <leader>fc :set ft=css<cr>
nmap <leader>fj :set ft=javascript<cr>
nmap <leader>fv :set ft=vue<cr>

"标签切换"
nmap <leader>h :tabp<cr>
nmap <leader>l :tabn<cr>
nmap <leader>j :bn<cr>
nmap <leader>k :bp<cr>


set cursorline	"设置光标高亮显示
autocmd InsertLeave * set cursorline
autocmd InsertEnter * set nocursorline 

" Change cursor shape in different modes
" For VTE compatible terminals (urxvt, st, xterm, gnome-terminal 3.x and others)
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" test option
hi Folded ctermbg=NONE
hi LineNr ctermbg=0

hi NonText ctermfg=247 guifg=#a73111 cterm=bold gui=bold
hi SpecialKey ctermfg=236 guifg=#654321

